all:	adjective/adjective.bn.dix adverb/adverb.bn.dix noun/noun.bn.dix postposition/postposition.bn.dix pronoun/pronoun.bn.dix proper-noun/proper-noun.bn.dix verb/verb.bn.dix determiner/determiner.bn.dix numerals/numerals.bn.dix conjunction/conjuction.bn.dix
	sh generate-dix.sh > ../apertium-bn-en.bn.dix
